name: Static Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: codeberg-small
    container:
      image: php:8.4-cli
    name: PHPStan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update -qq
          apt-get install -y -qq unzip git libzip-dev libsqlite3-dev
          docker-php-ext-install zip pdo pdo_sqlite

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
